export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_PARTICULAR_FILM_SUCCESS = 'FETCH_PARTICULAR_FILM_SUCCESS';
export const FETCH_FILMS_FAIL = 'FETCH_FILMS_FAIL';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_SORT_FILTER = 'SET_SORT_FILTER';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
