export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAIL = 'FETCH_FILMS_FAIL';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
